name: Android Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708
          packages: >-
            platforms;android-34
            build-tools;34.0.0
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      - name: Accept Licenses
        run: |
          yes | sdkmanager --licenses || true
      - name: Build APK
        run: ./gradlew assembleDebug
        working-directory: android
